/**
 * Color options under review (temporary). Each variant has a dark and a light
 * palette in the same model as Easy SSH Dark and Light, so the chosen one can
 * replace DARK and LIGHT in theme.ts directly. Pick one with the dev-only
 * easySsh.devPalette setting; unset keeps the current palettes.
 */
import { DARK, hex, LIGHT, type Palette, type ThemeKind } from './theme';

export type PaletteVariant = 'A' | 'B' | 'C' | 'D' | 'E' | 'F';

export interface VariantInfo {
  id: PaletteVariant;
  title: string;
  /** One line for the review. */
  summary: string;
  dark: Palette;
  light: Palette;
}

const VSCODE_DARK = hex('#1F1F1F');
const VSCODE_LIGHT = hex('#FFFFFF');

export const VARIANTS: Record<PaletteVariant, VariantInfo> = {
  A: {
    id: 'A',
    title: 'Neutral',
    summary: "No painted panel: VS Code's own terminal background, purple-pink only for the brand, accents and a soft selected-row tint",
    dark: {
      kind: 'dark',
      name: 'Easy SSH Neutral Dark',
      canvas: VSCODE_DARK,
      fg: {
        text: hex('#E6E6EA'),
        muted: hex('#9E9AAE'),
        accent: hex('#B39DFA'),
        accent2: hex('#F59AC8'),
        border: hex('#57506E'),
        success: hex('#86D99B'),
        warn: hex('#E9C46A'),
        error: hex('#F59393'),
        info: hex('#6FD3E3'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#C9C4DA'),
      },
      selection: hex('#2F2A42'),
      selectStyle: 'tint',
      danger: hex('#4A2026'),
      badgeFrom: hex('#8B5CF6'),
      badgeTo: hex('#EC4899'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Neutral Light',
      canvas: VSCODE_LIGHT,
      fg: {
        text: hex('#1F2328'),
        muted: hex('#5E5A6E'),
        accent: hex('#6D28D9'),
        accent2: hex('#BE185D'),
        border: hex('#B9A7EE'),
        success: hex('#1A6B35'),
        warn: hex('#8A4B00'),
        error: hex('#B91C1C'),
        info: hex('#155E75'),
        selText: hex('#1E1B4B'),
        selMuted: hex('#4F4A66'),
      },
      selection: hex('#EEE9FB'),
      selectStyle: 'tint',
      danger: hex('#FDE4E4'),
      badgeFrom: hex('#7C3AED'),
      badgeTo: hex('#DB2777'),
    },
  },
  B: {
    id: 'B',
    title: 'Pastel',
    summary: 'Soft lavender and rose on a muted lavender-grey panel, low-saturation selection bar',
    dark: {
      kind: 'dark',
      name: 'Easy SSH Pastel Dark',
      panel: hex('#24212E'),
      fg: {
        text: hex('#EEEAF6'),
        muted: hex('#A9A3BB'),
        accent: hex('#C9B8F5'),
        accent2: hex('#F4B4CF'),
        border: hex('#6B6285'),
        success: hex('#A8DDB5'),
        warn: hex('#EBD38F'),
        error: hex('#F2A7A7'),
        info: hex('#A3DCE6'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#D3CCE6'),
      },
      selection: hex('#3C3650'),
      selectStyle: 'tint',
      danger: hex('#4E2B33'),
      badgeFrom: hex('#B59CF0'),
      badgeTo: hex('#F0A3C4'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Pastel Light',
      panel: hex('#FAF7FC'),
      fg: {
        text: hex('#2E2A3A'),
        muted: hex('#686277'),
        accent: hex('#6E50B5'),
        accent2: hex('#A83E6E'),
        border: hex('#B9A9D8'),
        success: hex('#2E6B42'),
        warn: hex('#80520F'),
        error: hex('#A93A3A'),
        info: hex('#2C6370'),
        selText: hex('#2E2A3A'),
        selMuted: hex('#5A5468'),
      },
      selection: hex('#ECE3F6'),
      selectStyle: 'tint',
      danger: hex('#F9E1E6'),
      badgeFrom: hex('#9C84D6'),
      badgeTo: hex('#E08DB2'),
    },
  },
  C: {
    id: 'C',
    title: 'Graphite',
    summary: 'Charcoal/graphite panel, greys for structure, pink as the one strong accent with a dim rose selection bar',
    dark: {
      kind: 'dark',
      name: 'Easy SSH Graphite Dark',
      panel: hex('#25252A'),
      fg: {
        text: hex('#EDEDF0'),
        muted: hex('#9D9DA6'),
        accent: hex('#F472B6'),
        accent2: hex('#D8B4FE'),
        border: hex('#55555E'),
        success: hex('#86D99B'),
        warn: hex('#E9C46A'),
        error: hex('#F59393'),
        info: hex('#7DD3E0'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#E6CFDC'),
      },
      selection: hex('#5A2944'),
      danger: hex('#8F1D2C'),
      badgeFrom: hex('#EC4899'),
      badgeTo: hex('#A855F7'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Graphite Light',
      panel: hex('#F4F4F5'),
      fg: {
        text: hex('#18181B'),
        muted: hex('#55555E'),
        accent: hex('#BE185D'),
        accent2: hex('#7E22CE'),
        border: hex('#ABABB3'),
        success: hex('#1A6B35'),
        warn: hex('#8A4B00'),
        error: hex('#B91C1C'),
        info: hex('#155E75'),
        selText: hex('#18181B'),
        selMuted: hex('#4A4A52'),
      },
      selection: hex('#FBE3EF'),
      selectStyle: 'tint',
      danger: hex('#FDE4E4'),
      badgeFrom: hex('#DB2777'),
      badgeTo: hex('#9333EA'),
    },
  },
  D: {
    id: 'D',
    title: 'Neon',
    summary: 'Magenta-to-violet gradient accents on near-black; the selected row is a ▌ accent marker and bold text, no filled bar',
    dark: {
      kind: 'dark',
      name: 'Easy SSH Neon Dark',
      panel: hex('#0F0C16'),
      fg: {
        text: hex('#E9E4F5'),
        muted: hex('#8C849F'),
        accent: hex('#E879F9'),
        accent2: hex('#A78BFA'),
        border: hex('#583A75'),
        success: hex('#7EE2A0'),
        warn: hex('#F2CC60'),
        error: hex('#FF8F9C'),
        info: hex('#6EE0F0'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#B9B0CC'),
      },
      selection: hex('#0F0C16'),
      selectStyle: 'marker',
      marker: 'accent',
      danger: hex('#0F0C16'),
      badgeFrom: hex('#D946EF'),
      badgeTo: hex('#7C3AED'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Neon Light',
      panel: hex('#FDFBFF'),
      fg: {
        text: hex('#2A2236'),
        muted: hex('#6B6080'),
        accent: hex('#A21CAF'),
        accent2: hex('#6D28D9'),
        border: hex('#C4A8E2'),
        success: hex('#1A6B35'),
        warn: hex('#8A4B00'),
        error: hex('#B91C1C'),
        info: hex('#155E75'),
        selText: hex('#0E0816'),
        selMuted: hex('#4F4562'),
      },
      selection: hex('#FDFBFF'),
      selectStyle: 'marker',
      marker: 'accent',
      danger: hex('#FDFBFF'),
      badgeFrom: hex('#C026D3'),
      badgeTo: hex('#6D28D9'),
    },
  },
  E: {
    id: 'E',
    title: 'Indigo',
    summary: 'Cool deep-indigo panel and blue-violet structure, pink kept for highlights (prompt keys, times, cursor)',
    dark: {
      kind: 'dark',
      name: 'Easy SSH Indigo Dark',
      panel: hex('#141A33'),
      fg: {
        text: hex('#E8ECFF'),
        muted: hex('#9AA3C7'),
        accent: hex('#93A0FB'),
        accent2: hex('#F67FBE'),
        border: hex('#3F4C8F'),
        success: hex('#86E0A6'),
        warn: hex('#F0CF6E'),
        error: hex('#FB9C9C'),
        info: hex('#6FDBEB'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#D4DBFF'),
      },
      selection: hex('#2E3C85'),
      danger: hex('#9B1C2E'),
      badgeFrom: hex('#6366F1'),
      badgeTo: hex('#EC4899'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Indigo Light',
      panel: hex('#F2F4FF'),
      fg: {
        text: hex('#121A45'),
        muted: hex('#4C5683'),
        accent: hex('#4338CA'),
        accent2: hex('#BE185D'),
        border: hex('#A5B0F5'),
        success: hex('#1A6B35'),
        warn: hex('#8A4B00'),
        error: hex('#B91C1C'),
        info: hex('#155E75'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#E0E5FF'),
      },
      selection: hex('#4F46E5'),
      danger: hex('#C81E1E'),
      badgeFrom: hex('#4F46E5'),
      badgeTo: hex('#DB2777'),
    },
  },
  F: {
    id: 'F',
    title: 'Mono',
    summary: 'Minimal greys with a single pink accent: pink badge, "SSH", selection marker and keys; neutral tint selection',
    dark: {
      kind: 'dark',
      name: 'Easy SSH Mono Dark',
      panel: hex('#181818'),
      fg: {
        text: hex('#E5E5E5'),
        muted: hex('#999999'),
        accent: hex('#F2F2F2'),
        accent2: hex('#F472B6'),
        border: hex('#4D4D4D'),
        success: hex('#B4D6BC'),
        warn: hex('#DDCFA3'),
        error: hex('#F2A3A3'),
        info: hex('#A9D3DB'),
        selText: hex('#FFFFFF'),
        selMuted: hex('#C2C2C2'),
      },
      selection: hex('#2B2B2B'),
      selectStyle: 'tint',
      marker: 'accent2',
      danger: hex('#3D2226'),
      badgeFrom: hex('#EC4899'),
      badgeTo: hex('#EC4899'),
    },
    light: {
      kind: 'light',
      name: 'Easy SSH Mono Light',
      panel: hex('#FAFAFA'),
      fg: {
        text: hex('#171717'),
        muted: hex('#5E5E5E'),
        accent: hex('#262626'),
        accent2: hex('#C2185B'),
        border: hex('#B5B5B5'),
        success: hex('#2F6B3E'),
        warn: hex('#7A5300'),
        error: hex('#B42323'),
        info: hex('#2B6070'),
        selText: hex('#0A0A0A'),
        selMuted: hex('#4A4A4A'),
      },
      selection: hex('#EDEDED'),
      selectStyle: 'tint',
      marker: 'accent2',
      danger: hex('#FBE3E3'),
      badgeFrom: hex('#DB2777'),
      badgeTo: hex('#DB2777'),
    },
  },
};

export function parseVariant(value: unknown): PaletteVariant | undefined {
  return typeof value === 'string' && value in VARIANTS ? (value as PaletteVariant) : undefined;
}

/** The palette to draw: a review variant when one is picked, else Easy SSH Dark or Light. */
export function resolvePalette(kind: ThemeKind, variant?: PaletteVariant): Palette {
  if (variant) return VARIANTS[variant][kind];
  return kind === 'light' ? LIGHT : DARK;
}
